### ISSUE TITLE
kCFCgrowth_new.m

### ISSUE THREAD

**Issue by zeydabadi** [CrossD/PACE_matlab#1]
Hi,

Running the "kCFCgrowth_new.m" under MATLAB R2016a I receive the following error:

Error using fscanf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in datap (line 23)
  data_in = reshape(fscanf(fid,'%f'),[4,nrow]);

Error in kCFCgrowth_new (line 17)
[idsubj,idclass,data] = datap(file_in,nrow);

I hope someone help with a solution.
Thank you!

**Comment by hadjipantelis** [comment]
Hello @zeydabadi,

Thank you for reporting this issue. Can you please provide a minimum reproducible example so we can try and replicate the issue you experience? 
Can you also tell us know of the output of the `ver` command in your MATLAB terminal?

All the best,
Pantelis

**Comment by zeydabadi** [comment]
Thanks for your prompt response!
The OS is Win 10.
I downloaded the PACE toolbox as is instructed below:

PACE Package source:
Up-to-date zip version is available for download on the following Github repository:      https://github.com/functionaldata/PACE_matlab.  
Click Clone or download button and select DOWNLOAD ZIP to download the package.


And then added the PACE directory and its subdirectories to the MATLAB path.

Thanks,
Mahmoud

**Comment by zeydabadi** [comment]
it looks like that the datap() function is not able to find the growth.dat file.

**Comment by zeydabadi** [comment]
Also, there is this line of code in the "kCFCgrowth_new.m":
addpath(genpath('kcfc-PACE215'))
but there is no 'kcfc-PACE215' under the  /PACE_matlab-master

**Comment by hadjipantelis** [comment]
Hello Mahmood,

Apologies for this the omission. The file (`growth.dat`) that related to the `kFCF` example have been made available now. We are working on a new example for `kFCF` and unfortunately this older example file fell through the cracks. Thank you for raising this issue with us.

All the best,
Pantelis

**Comment by zeydabadi** [comment]
Hi Pantelis,

Thank you for follow up. Should I download the PACE package again?

Mahmoud

**Comment by zeydabadi** [comment]
Hi Pantelis,

I downloaded the PACE package again and the "kCFCgrowth_new.m" works fine now. Thank you for the fix.
A quick question: is there any documentation for this example? what are those output plots? I'm sorry if the questions are very basic.

Thank you!
Mahmoud

**Comment by hadjipantelis** [comment]
Hello Mahmoud,

Great! I am happy to hear that everything is working for you. 

Unfortunately that example is somewhat stand-alone and we do not have a vignette around it. 

If you have a particular question about using the methodology around kCFC (or another PACE-related methodology) I would suggest you drop an e-mail to the authors of the methodology with specific Stats questions. Alternative you can ask Statistics questions to a public forum like StackExchange's Cross-Validated. You can get good answers there too.

I will close this issue now but do not hesitate to open a new one if there is a problem with the code again. Thank you for the feedback; it helps us weed out issues we missed out.

All the best,
Pantelis
